#!/usr/bin/env bash
xhost +local:docker ; XSOCK=/tmp/.X11-unix ; XAUTH=/tmp/.docker.xauth ; xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge - ; docker run -it --device=/dev/video0 -e DISPLAY=$DISPLAY --env QT_X11_NO_MITSHM=1 \
-w /home/code -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -v /home/ywt01/Desktop/CVtoDocker:/home/code  \
-e XAUTHORITY=$XAUTH abc50111/opencv:4.2.0-gui
